In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.chdir(r"C:\Users\hanis\OneDrive\Desktop\Kamakshigari Hanish FWI")

import pandas as pd
data = pd.read_csv("train_data.csv")

In [3]:
data

,report_date,temperature,dew_point_temperature,relative_humidity,wind_speed,wind_direction,atmospheric_pressure,visibility,precipitation,rain_days,...,duff_moisture_code,drought_code,build_up_index,initial_spread_index,fire_weather_index,daily_severity_rating,country,latitude,longitude,elevation
0,27-08-2019 12:00,12.0,7.6,74.4,12.0,0,1015.13,30.0,2.60,0,...,6.9,51.1,10.3,0.9,0.6,0.0,United Kingdom,54.502224,-2.68500,252.0
1,06-06-2018 12:00,11.1,1.7,52.0,22.1,200,1010.80,38.6,1.50,0,...,14.8,104.2,21.9,1.7,2.7,0.2,Canada,55.200000,-119.40000,745.0
2,11-10-2014 12:00,2.9,2.3,95.0,1.9,250,1018.19,27.7,0.00,2,...,3.1,330.1,6.1,0.1,0.0,0.0,Canada,49.820000,-74.98000,381.1
3,11-09-2015 12:00,22.1,11.1,49.8,9.5,267,1015.79,23.9,0.00,4,...,11.4,282.9,20.7,3.8,6.3,0.7,Canada,54.280000,-111.45000,619.0
4,22-06-2016 12:00,17.0,10.0,63.6,35.2,260,1016.70,16.1,0.00,1,...,107.4,482.9,138.1,15.6,47.7,25.4,United States,37.618805,-122.37542,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,02-10-2017 12:00,11.1,-0.8,44.0,19.6,330,1030.60,23.2,0.00,2,...,8.3,205.3,15.1,6.8,8.9,1.3,Canada,47.990000,-66.33417,40.0
1048571,20-09-2014 12:00,9.2,4.1,70.0,9.3,150,1017.10,16.5,0.00,1,...,4.8,190.9,9.1,1.6,0.9,0.0,Canada,47.420000,-68.32000,154.2
1048572,16-09-2019 12:00,16.0,11.0,72.4,11.1,320,1006.10,14.5,0.00,1,...,9.6,250.3,17.4,1.4,1.5,0.1,Canada,53.666668,-113.46667,687.9
1048573,14-07-2018 12:00,26.1,21.7,76.8,14.8,60,1019.10,16.1,9.42,0,...,15.0,86.8,20.9,0.8,0.8,0.0,United States,42.551193,-94.19183,352.4
1048574,28-05-2017 12:00,19.0,9.0,52.5,14.8,300,1017.60,14.5,0.00,4,...,5.5,24.4,7.1,3.5,3.1,0.2,Canada,54.290000,-130.44000,35.4

In [4]:
data.columns

Index(['report_date', 'temperature', 'dew_point_temperature',
       'relative_humidity', 'wind_speed', 'wind_direction',
       'atmospheric_pressure', 'visibility', 'precipitation', 'rain_days',
       'snow_on_ground', 'fine_fuel_moisture_code', 'duff_moisture_code',
       'drought_code', 'build_up_index', 'initial_spread_index',
       'fire_weather_index', 'daily_severity_rating', 'country', 'latitude',
       'longitude', 'elevation'],
      dtype='object')

In [5]:
data['FFMC__TEMP'] = data['temperature'] * data['fine_fuel_moisture_code']
data['FFMC_RH'] = data['relative_humidity'] * data['fine_fuel_moisture_code']
data['RH_TEMP'] = data['temperature'] * data['relative_humidity']
data['RD_FFMC'] = data['fine_fuel_moisture_code'] * data['rain_days']
data['DC_RD'] = data['drought_code'] * data['rain_days']
data['WS_TENP'] = data['wind_speed'] * data['fine_fuel_moisture_code']
data['IST_WS'] = data['wind_speed'] * data['initial_spread_index']
data['ISI_FFMC'] = data['initial_spread_index'] * data['fine_fuel_moisture_code']
data['ISI_RH'] = data['initial_spread_index'] * data['relative_humidity']
data['DMC_TEMP'] = data['duff_moisture_code'] * data['temperature']
data['DMC_RD'] = data['duff_moisture_code'] * data['rain_days']
data['RD_TEMP'] = data['rain_days'] * data['temperature']
data['DMC_DC'] = data['drought_code'] * data['duff_moisture_code']
data['BUI_DC'] = data['drought_code'] * data['build_up_index']
data['BUI_DMC'] = data['duff_moisture_code'] * data['build_up_index']

In [6]:
data

,report_date,temperature,dew_point_temperature,relative_humidity,wind_speed,wind_direction,atmospheric_pressure,visibility,precipitation,rain_days,...,WS_TENP,IST_WS,ISI_FFMC,ISI_RH,DMC_TEMP,DMC_RD,RD_TEMP,DMC_DC,BUI_DC,BUI_DMC
0,27-08-2019 12:00,12.0,7.6,74.4,12.0,0,1015.13,30.0,2.60,0,...,769.20,10.80,57.69,66.96,82.80,0.0,0.0,352.59,526.33,71.07
1,06-06-2018 12:00,11.1,1.7,52.0,22.1,200,1010.80,38.6,1.50,0,...,1463.02,37.57,112.54,88.40,164.28,0.0,0.0,1542.16,2281.98,324.12
2,11-10-2014 12:00,2.9,2.3,95.0,1.9,250,1018.19,27.7,0.00,2,...,84.17,0.19,4.43,9.50,8.99,6.2,5.8,1023.31,2013.61,18.91
3,11-09-2015 12:00,22.1,11.1,49.8,9.5,267,1015.79,23.9,0.00,4,...,815.10,36.10,326.04,189.24,251.94,45.6,88.4,3225.06,5856.03,235.98
4,22-06-2016 12:00,17.0,10.0,63.6,35.2,260,1016.70,16.1,0.00,1,...,3048.32,549.12,1350.96,992.16,1825.80,107.4,17.0,51863.46,66688.49,14831.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,02-10-2017 12:00,11.1,-0.8,44.0,19.6,330,1030.60,23.2,0.00,2,...,1691.48,133.28,586.84,299.20,92.13,16.6,22.2,1703.99,3100.03,125.33
1048571,20-09-2014 12:00,9.2,4.1,70.0,9.3,150,1017.10,16.5,0.00,1,...,731.91,14.88,125.92,112.00,44.16,4.8,9.2,916.32,1737.19,43.68
1048572,16-09-2019 12:00,16.0,11.0,72.4,11.1,320,1006.10,14.5,0.00,1,...,835.83,15.54,105.42,101.36,153.60,9.6,16.0,2402.88,4355.22,167.04
1048573,14-07-2018 12:00,26.1,21.7,76.8,14.8,60,1019.10,16.1,9.42,0,...,874.68,11.84,47.28,61.44,391.50,0.0,0.0,1302.00,1814.12,313.50
1048574,28-05-2017 12:00,19.0,9.0,52.5,14.8,300,1017.60,14.5,0.00,4,...,1232.84,51.80,291.55,183.75,104.50,22.0,76.0,134.20,173.24,39.05

In [7]:
df_encoded = pd.get_dummies(data, columns=['country'], dtype=int)

In [8]:
df_encoded

,report_date,temperature,dew_point_temperature,relative_humidity,wind_speed,wind_direction,atmospheric_pressure,visibility,precipitation,rain_days,...,DMC_RD,RD_TEMP,DMC_DC,BUI_DC,BUI_DMC,country_Canada,country_France,country_Spain,country_United Kingdom,country_United States
0,27-08-2019 12:00,12.0,7.6,74.4,12.0,0,1015.13,30.0,2.60,0,...,0.0,0.0,352.59,526.33,71.07,0,0,0,1,0
1,06-06-2018 12:00,11.1,1.7,52.0,22.1,200,1010.80,38.6,1.50,0,...,0.0,0.0,1542.16,2281.98,324.12,1,0,0,0,0
2,11-10-2014 12:00,2.9,2.3,95.0,1.9,250,1018.19,27.7,0.00,2,...,6.2,5.8,1023.31,2013.61,18.91,1,0,0,0,0
3,11-09-2015 12:00,22.1,11.1,49.8,9.5,267,1015.79,23.9,0.00,4,...,45.6,88.4,3225.06,5856.03,235.98,1,0,0,0,0
4,22-06-2016 12:00,17.0,10.0,63.6,35.2,260,1016.70,16.1,0.00,1,...,107.4,17.0,51863.46,66688.49,14831.94,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,02-10-2017 12:00,11.1,-0.8,44.0,19.6,330,1030.60,23.2,0.00,2,...,16.6,22.2,1703.99,3100.03,125.33,1,0,0,0,0
1048571,20-09-2014 12:00,9.2,4.1,70.0,9.3,150,1017.10,16.5,0.00,1,...,4.8,9.2,916.32,1737.19,43.68,1,0,0,0,0
1048572,16-09-2019 12:00,16.0,11.0,72.4,11.1,320,1006.10,14.5,0.00,1,...,9.6,16.0,2402.88,4355.22,167.04,1,0,0,0,0
1048573,14-07-2018 12:00,26.1,21.7,76.8,14.8,60,1019.10,16.1,9.42,0,...,0.0,0.0,1302.00,1814.12,313.50,0,0,0,0,1
1048574,28-05-2017 12:00,19.0,9.0,52.5,14.8,300,1017.60,14.5,0.00,4,...,22.0,76.0,134.20,173.24,39.05,1,0,0,0,0

In [9]:
df_encoded.columns

Index(['report_date', 'temperature', 'dew_point_temperature',
       'relative_humidity', 'wind_speed', 'wind_direction',
       'atmospheric_pressure', 'visibility', 'precipitation', 'rain_days',
       'snow_on_ground', 'fine_fuel_moisture_code', 'duff_moisture_code',
       'drought_code', 'build_up_index', 'initial_spread_index',
       'fire_weather_index', 'daily_severity_rating', 'latitude', 'longitude',
       'elevation', 'FFMC__TEMP', 'FFMC_RH', 'RH_TEMP', 'RD_FFMC', 'DC_RD',
       'WS_TENP', 'IST_WS', 'ISI_FFMC', 'ISI_RH', 'DMC_TEMP', 'DMC_RD',
       'RD_TEMP', 'DMC_DC', 'BUI_DC', 'BUI_DMC', 'country_Canada',
       'country_France', 'country_Spain', 'country_United Kingdom',
       'country_United States'],
      dtype='object')

In [10]:
data = df_encoded

In [11]:
data.columns

Index(['report_date', 'temperature', 'dew_point_temperature',
       'relative_humidity', 'wind_speed', 'wind_direction',
       'atmospheric_pressure', 'visibility', 'precipitation', 'rain_days',
       'snow_on_ground', 'fine_fuel_moisture_code', 'duff_moisture_code',
       'drought_code', 'build_up_index', 'initial_spread_index',
       'fire_weather_index', 'daily_severity_rating', 'latitude', 'longitude',
       'elevation', 'FFMC__TEMP', 'FFMC_RH', 'RH_TEMP', 'RD_FFMC', 'DC_RD',
       'WS_TENP', 'IST_WS', 'ISI_FFMC', 'ISI_RH', 'DMC_TEMP', 'DMC_RD',
       'RD_TEMP', 'DMC_DC', 'BUI_DC', 'BUI_DMC', 'country_Canada',
       'country_France', 'country_Spain', 'country_United Kingdom',
       'country_United States'],
      dtype='object')

In [12]:
data.shape

(1048575, 41)